backend:
  build: ./backend
  command: python manage.py runserver 0.0.0.0:3000
  environment:
    NODE_ENV: development
  ports:
    - '3000:3000'
  volumes:
    - ./backend:/usr/src/app:ro

frontend:
  build: ./frontend
  command: npm start
  environment:
    NODE_ENV: development
  ports:
    - '3001:3001'
    - '35729:35729'
  volumes:
    - ./backend:/usr/src/backend:rw
    - ./frontend:/usr/src/app:rw